FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Explicitly tell Docker to look for these
ENV SPRING_SECURITY_JWT_SECRET_KEY=$SPRING_SECURITY_JWT_SECRET_KEY
ENV APP_ENCRYPTION_SECRET_KEY=$APP_ENCRYPTION_SECRET_KEY
ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD

EXPOSE 8080
ENTRYPOINT java -jar app.jar