spring.application.name=backend-learning

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2005}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
spring.security.jwt.secret-key=${SPRING_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
spring.security.jwt.expiration=${JWT_EXPIRATION:86400000}

# ENCRYPTION
app.encryption.secret-key=${APP_ENCRYPTION_SECRET_KEY:SatyakiDeSecretKey20050706000000}

# SERVER
server.port=${PORT:8080}
spring.mvc.pathmatch.use-suffix-pattern=false

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
